language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache

branches:
  only:
    - master
    - dev
    - /^\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
    - php: 7.1
      env: SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
    - php: 7.2
      env: SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

before_install:
    - phpenv config-rm xdebug.ini

install: composer update $COMPOSER_FLAGS

script: ./phpunit
